export const SHIFT_META = {
  morning: { label: 'Ca sáng', time: '07:00 - 12:00', color: '#0D9488', bg: '#F0FDFA', border: '#CCFBF1' },
  afternoon: { label: 'Ca chiều', time: '12:00 - 17:00', color: '#D97706', bg: '#FFFBEB', border: '#FEF3C7' },
  evening: { label: 'Ca tối', time: '17:00 - 22:00', color: '#7C3AED', bg: '#F5F3FF', border: '#EDE9FE' },
  custom: { label: 'Ca tự chọn', time: 'Tùy chỉnh', color: '#4B5563', bg: '#F3F4F6', border: '#E5E7EB' },
};

export const STATUS_META = {
  confirmed: { label: 'Có mặt', color: '#16A34A', bg: '#F0FDF4', border: '#DCFCE7' },
  absent: { label: 'Vắng mặt', color: '#DC2626', bg: '#FEF2F2', border: '#FEE2E2' },
};

export const STAFF_OPTIONS = [
  { value: 'all', label: 'Tất cả nhân viên' },
  { value: 'admin-gpp', label: 'Admin GPP' },
  { value: 'duoc-si-minh', label: 'Dược sĩ Minh' },
  { value: 'duoc-si-lan', label: 'Dược sĩ Lan' },
  { value: 'thu-ngan-hanh', label: 'Thu ngân Hạnh' },
];

export const WEEK_DAYS = [
  { key: 'mon', label: 'Thứ 2', date: '25/05' },
  { key: 'tue', label: 'Thứ 3', date: '26/05' },
  { key: 'wed', label: 'Thứ 4', date: '27/05' },
  { key: 'thu', label: 'Thứ 5', date: '28/05' },
  { key: 'fri', label: 'Thứ 6', date: '29/05' },
  { key: 'sat', label: 'Thứ 7', date: '30/05' },
  { key: 'sun', label: 'CN', date: '31/05' },
];

export const SCHEDULE_SHIFTS = [
  {
    id: 'SCH-001',
    day: 'mon',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    shiftType: 'morning',
    area: 'Quầy tư vấn',
    status: 'confirmed',
    note: 'Phụ trách tư vấn thuốc kê đơn',
  },
  {
    id: 'SCH-002',
    day: 'mon',
    staffId: 'thu-ngan-hanh',
    staffName: 'Thu ngân Hạnh',
    role: 'Thu ngân',
    shiftType: 'afternoon',
    area: 'POS',
    status: 'confirmed',
    note: 'Đối soát cuối ca',
  },
  {
    id: 'SCH-003',
    day: 'tue',
    staffId: 'admin-gpp',
    staffName: 'Admin GPP',
    role: 'Quản lý',
    shiftType: 'morning',
    area: 'Kho',
    status: 'confirmed',
    note: 'Kiểm kê tồn kho nhanh',
  },
  {
    id: 'SCH-004',
    day: 'tue',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    shiftType: 'evening',
    area: 'Quầy thuốc',
    status: 'pending',
    note: 'Chờ xác nhận đổi ca',
  },
  {
    id: 'SCH-005',
    day: 'wed',
    staffId: 'duoc-si-lan',
    staffName: 'Dược sĩ Lan',
    role: 'Dược sĩ',
    shiftType: 'afternoon',
    area: 'Quầy tư vấn',
    status: 'confirmed',
    note: 'Phụ trách nhập đơn thuốc',
  },
  {
    id: 'SCH-006',
    day: 'thu',
    staffId: 'thu-ngan-hanh',
    staffName: 'Thu ngân Hạnh',
    role: 'Thu ngân',
    shiftType: 'morning',
    area: 'POS',
    status: 'absent',
    note: 'Xin nghỉ có phép',
  },
  {
    id: 'SCH-007',
    day: 'fri',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    shiftType: 'afternoon',
    area: 'Quầy thuốc',
    status: 'confirmed',
    note: 'Ca tăng cường cuối tuần',
  },
  {
    id: 'SCH-008',
    day: 'sat',
    staffId: 'duoc-si-lan',
    staffName: 'Dược sĩ Lan',
    role: 'Dược sĩ',
    shiftType: 'evening',
    area: 'Quầy thuốc',
    status: 'confirmed',
    note: 'Theo dõi thuốc cận hạn',
  },
];
