export const PAYROLL_STATUS_META = {
  draft: {
    label: 'Nháp',
    color: 'var(--color-text-secondary)',
    bg: 'var(--color-bg-subtle)',
    border: 'var(--color-border)',
  },
  pending: {
    label: 'Chờ duyệt',
    color: 'var(--color-warning)',
    bg: 'var(--color-warning-bg)',
    border: 'var(--color-warning)',
  },
  approved: {
    label: 'Đã duyệt',
    color: 'var(--color-primary)',
    bg: 'var(--color-primary-light)',
    border: 'var(--color-primary-border)',
  },
  paid: {
    label: 'Đã chi trả',
    color: 'var(--color-profit)',
    bg: 'var(--color-profit-bg)',
    border: 'var(--color-profit)',
  },
};

export const PAYROLL_RECORDS = [
  {
    id: 'PR-2026-05-001',
    period: '2026-05',
    staffId: 'admin-gpp',
    staffName: 'Admin GPP',
    role: 'Quản lý',
    workDays: 26,
    overtimeHours: 6,
    baseSalary: 14000000,
    allowance: 1500000,
    bonus: 900000,
    deductions: 420000,
    netPay: 15980000,
    status: 'approved',
    paidAt: null,
    note: 'Thưởng kiểm kê kho cuối tháng',
  },
  {
    id: 'PR-2026-05-002',
    period: '2026-05',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    workDays: 25,
    overtimeHours: 3.5,
    baseSalary: 10500000,
    allowance: 900000,
    bonus: 550000,
    deductions: 260000,
    netPay: 11690000,
    status: 'paid',
    paidAt: '2026-05-25',
    note: 'Đã chuyển khoản theo bảng lương tháng 05',
  },
  {
    id: 'PR-2026-05-003',
    period: '2026-05',
    staffId: 'duoc-si-lan',
    staffName: 'Dược sĩ Lan',
    role: 'Dược sĩ',
    workDays: 23,
    overtimeHours: 0,
    baseSalary: 9800000,
    allowance: 850000,
    bonus: 300000,
    deductions: 520000,
    netPay: 10430000,
    status: 'pending',
    paidAt: null,
    note: 'Cần xác nhận một ca thiếu chấm công',
  },
  {
    id: 'PR-2026-05-004',
    period: '2026-05',
    staffId: 'thu-ngan-hanh',
    staffName: 'Thu ngân Hạnh',
    role: 'Thu ngân',
    workDays: 24,
    overtimeHours: 2,
    baseSalary: 7800000,
    allowance: 650000,
    bonus: 250000,
    deductions: 180000,
    netPay: 8520000,
    status: 'draft',
    paidAt: null,
    note: 'Đang rà soát phụ cấp ca tối',
  },
  {
    id: 'PR-2026-04-001',
    period: '2026-04',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    workDays: 26,
    overtimeHours: 4,
    baseSalary: 10500000,
    allowance: 900000,
    bonus: 650000,
    deductions: 240000,
    netPay: 11810000,
    status: 'paid',
    paidAt: '2026-04-26',
    note: 'Hoàn tất chi trả kỳ tháng 04',
  },
];

export const PAYROLL_STAFF_OPTIONS = [
  { value: 'all', label: 'Tất cả nhân viên' },
  { value: 'admin-gpp', label: 'Admin GPP' },
  { value: 'duoc-si-minh', label: 'Dược sĩ Minh' },
  { value: 'duoc-si-lan', label: 'Dược sĩ Lan' },
  { value: 'thu-ngan-hanh', label: 'Thu ngân Hạnh' },
];

export const PAYROLL_PERIOD_OPTIONS = [
  { value: 'all', label: 'Tất cả kỳ lương' },
  { value: '2026-05', label: 'Tháng 05/2026' },
  { value: '2026-04', label: 'Tháng 04/2026' },
];
