export const ACTION_META = {
  login: { label: 'Đăng nhập', color: 'var(--color-primary)', bg: 'var(--color-primary-light)', border: 'var(--color-primary-border)' },
  create: { label: 'Tạo mới', color: 'var(--color-profit)', bg: 'var(--color-profit-bg)', border: 'var(--color-profit)' },
  update: { label: 'Cập nhật', color: 'var(--color-inventory)', bg: 'var(--color-inventory-bg)', border: 'var(--color-inventory)' },
  delete: { label: 'Xóa/khóa', color: 'var(--color-debt)', bg: 'var(--color-debt-bg)', border: 'var(--color-debt)' },
  export: { label: 'Xuất file', color: 'var(--color-warning)', bg: 'var(--color-warning-bg)', border: 'var(--color-warning)' },
};

export const MODULE_LABELS = {
  auth: 'Đăng nhập',
  medicine: 'Thuốc',
  sale: 'Bán hàng',
  inventory: 'Kho',
  supplier: 'Nhà cung cấp',
  user: 'Người dùng',
  report: 'Báo cáo',
};

export const ACTIVITY_LOGS = [
  {
    id: 'ACT-001',
    timestamp: '2026-05-26 10:24',
    userName: 'Admin GPP',
    userRole: 'Quản trị',
    action: 'update',
    module: 'medicine',
    target: 'Paracetamol 500mg',
    description: 'Cập nhật giá bán từ 20.000đ lên 22.000đ',
    ipAddress: '192.168.1.24',
    device: 'Chrome / Windows',
    status: 'success',
  },
  {
    id: 'ACT-002',
    timestamp: '2026-05-26 09:58',
    userName: 'Dược sĩ Minh',
    userRole: 'Dược sĩ',
    action: 'create',
    module: 'sale',
    target: 'HD202605260004',
    description: 'Tạo hóa đơn bán hàng cho khách lẻ',
    ipAddress: '192.168.1.31',
    device: 'Chrome / Windows',
    status: 'success',
  },
  {
    id: 'ACT-003',
    timestamp: '2026-05-26 09:35',
    userName: 'Admin GPP',
    userRole: 'Quản trị',
    action: 'export',
    module: 'report',
    target: 'Báo cáo NXT',
    description: 'Xuất dữ liệu báo cáo nhập xuất tồn tháng 05/2026',
    ipAddress: '192.168.1.24',
    device: 'Chrome / Windows',
    status: 'success',
  },
  {
    id: 'ACT-004',
    timestamp: '2026-05-25 16:12',
    userName: 'Admin GPP',
    userRole: 'Quản trị',
    action: 'delete',
    module: 'user',
    target: 'customer@example.com',
    description: 'Khóa tài khoản người dùng không hoạt động',
    ipAddress: '192.168.1.24',
    device: 'Chrome / Windows',
    status: 'warning',
  },
  {
    id: 'ACT-005',
    timestamp: '2026-05-25 14:08',
    userName: 'Dược sĩ Minh',
    userRole: 'Dược sĩ',
    action: 'create',
    module: 'inventory',
    target: 'PN20260525001',
    description: 'Tạo phiếu nhập kho từ nhà cung cấp IMEXPHARM',
    ipAddress: '192.168.1.31',
    device: 'Safari / iPad',
    status: 'success',
  },
  {
    id: 'ACT-006',
    timestamp: '2026-05-25 08:02',
    userName: 'duocsi@pharmacy.com',
    userRole: 'Dược sĩ',
    action: 'login',
    module: 'auth',
    target: 'Phiên đăng nhập',
    description: 'Đăng nhập hệ thống từ thiết bị đã xác thực',
    ipAddress: '192.168.1.31',
    device: 'Chrome / Windows',
    status: 'success',
  },
];
