export const STATUS_META = {
  complete: { label: 'Đủ công', color: 'var(--color-profit)', bg: 'var(--color-profit-bg)', border: 'var(--color-profit)' },
  late: { label: 'Đi muộn', color: 'var(--color-warning)', bg: 'var(--color-warning-bg)', border: 'var(--color-warning)' },
  missing: { label: 'Thiếu chấm công', color: 'var(--color-debt)', bg: 'var(--color-debt-bg)', border: 'var(--color-debt)' },
  overtime: { label: 'Tăng ca', color: 'var(--color-primary)', bg: 'var(--color-primary-light)', border: 'var(--color-primary-border)' },
};

export const METHOD_META = {
  pos: 'POS',
  manual: 'Thủ công',
  mobile: 'Mobile',
};

export const TIMESHEET_RECORDS = [
  {
    id: 'TS-001',
    date: '2026-05-26',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    shift: 'Ca sáng',
    scheduledTime: '07:00 - 12:00',
    checkIn: '06:58',
    checkOut: '12:05',
    workHours: 5.1,
    overtimeHours: 0,
    status: 'complete',
    method: 'pos',
    note: 'Chấm công tại quầy POS',
  },
  {
    id: 'TS-002',
    date: '2026-05-26',
    staffId: 'thu-ngan-hanh',
    staffName: 'Thu ngân Hạnh',
    role: 'Thu ngân',
    shift: 'Ca chiều',
    scheduledTime: '12:00 - 17:00',
    checkIn: '12:18',
    checkOut: '17:02',
    workHours: 4.7,
    overtimeHours: 0,
    status: 'late',
    method: 'pos',
    note: 'Đi muộn 18 phút',
  },
  {
    id: 'TS-003',
    date: '2026-05-25',
    staffId: 'admin-gpp',
    staffName: 'Admin GPP',
    role: 'Quản lý',
    shift: 'Ca sáng',
    scheduledTime: '07:00 - 12:00',
    checkIn: '07:04',
    checkOut: '13:10',
    workHours: 6.1,
    overtimeHours: 1.1,
    status: 'overtime',
    method: 'manual',
    note: 'Duyệt tăng ca kiểm kê kho',
  },
  {
    id: 'TS-004',
    date: '2026-05-25',
    staffId: 'duoc-si-lan',
    staffName: 'Dược sĩ Lan',
    role: 'Dược sĩ',
    shift: 'Ca tối',
    scheduledTime: '17:00 - 22:00',
    checkIn: '17:00',
    checkOut: null,
    workHours: 0,
    overtimeHours: 0,
    status: 'missing',
    method: 'mobile',
    note: 'Thiếu chấm công ra',
  },
  {
    id: 'TS-005',
    date: '2026-05-24',
    staffId: 'duoc-si-minh',
    staffName: 'Dược sĩ Minh',
    role: 'Dược sĩ',
    shift: 'Ca chiều',
    scheduledTime: '12:00 - 17:00',
    checkIn: '11:55',
    checkOut: '17:00',
    workHours: 5,
    overtimeHours: 0,
    status: 'complete',
    method: 'pos',
    note: 'Đủ công',
  },
];

export const STAFF_OPTIONS = [
  { value: 'all', label: 'Tất cả nhân viên' },
  { value: 'admin-gpp', label: 'Admin GPP' },
  { value: 'duoc-si-minh', label: 'Dược sĩ Minh' },
  { value: 'duoc-si-lan', label: 'Dược sĩ Lan' },
  { value: 'thu-ngan-hanh', label: 'Thu ngân Hạnh' },
];
